name: Merge Description Issue Id's Check

on:
  pull_request:
    branches:
      - main

jobs:
  check-merge-ids:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Extract Jira Issue IDs from PR description
      id: extract_issue_ids
      run: |
        CM_REGEX='#CM-[0-9]+'
        JIRA_REGEX='#([A-Z]+[0-9]+(-[0-9]+)?)'

        # Get the pull request description
        PR_DESCRIPTION="${{ github.event.pull_request.body }}"

        # Extract all matching JIRA IDs
        CM_IDS=$(echo "$PR_DESCRIPTION" | grep -oE "$CM_REGEX" | tr -d '#' | paste -sd ',' -)
        OTHER_IDS=$(echo "$PR_DESCRIPTION" | grep -oE "$JIRA_REGEX" | grep -vE "$CM_REGEX" | tr -d '#' | paste -sd ',' -)

        if [ -z "$CM_IDS" ]; then
          echo "ERROR: No valid change-management JIRA issue found in PR description."
          exit 1
        fi

        # if [ -z "$OTHER_IDS" ]; then
        #   echo "ERROR: No valid JIRA project issue found in PR description."
        #   exit 1
        # fi

        # Extract repo name
        REPO_NAME=$(basename -s .git `git config --get remote.origin.url`)

        echo "Change-management IDs: $CM_IDS"
        echo "Other JIRA issue IDs: $OTHER_IDS"
        echo "Repo Name: $REPO_NAME"
        echo "cm_ids=$CM_IDS" >> $GITHUB_ENV
        echo "jira_ids=$OTHER_IDS" >> $GITHUB_ENV
        echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Check IDs
      env:
        EMAIL: ${{ secrets.EMAIL }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        CM_IDS: ${{ env.cm_ids }}
        JIRRA_IDS: ${{ env.jira_ids }}
        REPO_NAME: ${{ env.repo_name }}
      run: node checkMergeDescriptionIDs.js
